#
# Make sure to check the documentation at http://goreleaser.com
#

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/aztfmod/rover/pkg/version.Value={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    binary: rover

# replaces goos values with more readable names
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: '{{ time "2006-01-02" }}-snap'

release:
  draft: false
  prerelease: false
  header: |
    ## 🐶 Rover v2 Release

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^[Mm]erge"
      - "[Rr]eadme"
      - "[Ll]int"
