#
# Make sure to check the documentation at http://goreleaser.com
#

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{ .version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

# replaces goos values with more readable names
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
