# General place to put things
tempDir: /tmp

# Terraform options
terraform:
  # If terraform not found in system PATH, should we carry out a local install?
  install: true
  # Where to install terraform into, if install is true
  installPath: ./bin

# Remote state nonsense
state:
  storage-account: __CHANGE_ME__
  resource-group: __CHANGE_ME__
  container: tfstate
  access-key: __CHANGE_ME__

# Authentication to Azure, not all keys are required
# Run `rover login --help` for details
auth:
  client-cert-password:
  client-cert-path:
  client-id:
  client-secret:
  environment:
  msi-endpoint:
  subscription-id:
  tenant-id:
  use-msi: false
