name: CI builds

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run lint and format checks
        #run: make lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  ci-build:
    name: Run Tests and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        if: ${{ !env.ACT }}
        with:
          go-version: 1.16

      - name: Run tests
        run: make test

      - name: Run build
        run: make build
