name: CI builds

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run lint and format checks
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  ci-build:
    name: Run Tests and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        if: ${{ !env.ACT }}
        with:
          go-version: 1.16

      - name: Run tests
        # Removed until we can set up azure cli and login etc in pipeline
        #run: echo "Tests disabled in CI at the present time :("
        run: make test

      - name: Run build
        run: make build

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Azure Credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Go
        uses: actions/setup-go@v2
        if: ${{ !env.ACT }}
        with:
          go-version: 1.16

      - name: Checkout CAF Landing Zones
        run: git clone https://github.com/azure/caf-terraform-landingzones.git ~/.rover/caf-terraform-landingzones

      - name: Run integration tests in integration folder
        run: go test -timeout 600s -tags integration github.com/aztfmod/rover/test/integration
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
