name: Release Binaries

on:
  pushzzz:
    tags:
      - "*"

jobs:
  auto-release:
    env:
      IMAGE_REG: symphonydev.azurecr.io
      REGISTRY_USER: symphonydev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        if: ${{ !env.ACT }}
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: ${{ !env.ACT }}
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Dev Containers Images
        run: |
          echo ${{ secrets.REGISTRY_PWD }} | docker login $IMAGE_REG -u $REGISTRY_USER --password-stdin
          make image IMAGE_TAG=${GITHUB_REF##*/}
          make image IMAGE_TAG=latest
          make image-dev IMAGE_TAG=${GITHUB_REF##*/}
          make image-dev IMAGE_TAG=latest
          make push IMAGE_TAG=${GITHUB_REF##*/}
          make push IMAGE_TAG=latest

      - name: Run GoReleaser (local / act)
        if: ${{ env.ACT }}
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
